# Generated by Django 5.2 on 2025-05-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_left_banner_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_right_banner_offer',
            field=models.BooleanField(default=False),
        ),
    ]
