# Generated by Django 5.2 on 2025-05-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_description',
            field=models.TextField(blank=True),
        ),
    ]
