# Generated by Django 5.2 on 2025-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
