# Generated by Django 5.2 on 2025-05-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_carouselitem_description_carouselitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='sub_description',
            field=models.TextField(blank=True),
        ),
    ]
