# Generated by Django 5.2 on 2025-06-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
