# Generated by Django 5.2.4 on 2026-06-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="sound_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="variation_sounds/",
                verbose_name="Sound File",
            ),
        ),
    ]
