# Generated by Django 5.2.4 on 2026-06-03 09:43

import storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_variation_sound_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="sound_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storage_backends.VariationSoundStorage(),
                upload_to="variation_sounds/",
                verbose_name="Sound File",
            ),
        ),
    ]
