# Generated by Django 5.2.4 on 2026-06-04 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0006_insidesubcategory"),
        ("store", "0014_alter_variation_sound_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inside_sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.insidesubcategory",
            ),
        ),
    ]
