# Generated by Django 5.2.4 on 2026-06-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_remove_product_category_product_main_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
