# Generated by Django 5.2.4 on 2026-06-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_gallery_alter_websitereview_rating_galleryimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "gallery", "verbose_name_plural": "gallery"},
        ),
    ]
