# Generated by Django 5.2.4 on 2026-06-16 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_alter_gallery_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="productgallery",
            name="variation",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for product‑level images",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="store.variation",
            ),
        ),
    ]
