# Generated by Django 5.2.4 on 2026-06-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0022_remove_productgallery_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="weight",
            field=models.FloatField(default=0.0, help_text="Weight in kg"),
        ),
    ]
