# Generated by Django 5.2.4 on 2026-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_variation_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.FloatField(default=0.0, help_text="Weight in kg"),
        ),
    ]
