# Generated by Django 5.2.4 on 2026-06-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_product_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="packaging_weight",
            field=models.FloatField(default=0.0, help_text="Weight in kg"),
        ),
        migrations.AddField(
            model_name="variation",
            name="packaging_weight",
            field=models.FloatField(default=0.0, help_text="Weight in kg"),
        ),
    ]
