# Generated by Django 5.2.4 on 2026-06-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_product_packaging_weight_variation_packaging_weight"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CarouselItem",
        ),
    ]
