# Generated by Django 5.2.4 on 2026-05-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="state",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
