# Generated by Django 5.2 on 2025-05-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_maincategory_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
    ]
