# Generated by Django 5.2.4 on 2026-06-04 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_alter_subcategory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsideSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insidesubcategories",
                        to="category.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inside Sub Categories",
            },
        ),
    ]
