# Generated by Django 5.2.4 on 2026-06-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0006_insidesubcategory"),
        ("store", "0016_remove_product_category_product_main_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
