# Generated by Django 5.2.4 on 2026-06-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0007_delete_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maincategory",
            options={},
        ),
        migrations.AddField(
            model_name="maincategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
