# Generated by Django 5.2.4 on 2026-06-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0008_alter_maincategory_options_maincategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maincategory",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
