# Generated by Django 5.2.4 on 2026-06-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0009_alter_maincategory_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maincategory",
            options={"verbose_name_plural": "Main Categories"},
        ),
    ]
