# Generated by Django 5.2.4 on 2026-06-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0010_alter_maincategory_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LeftBanner",
        ),
        migrations.DeleteModel(
            name="RightBanner",
        ),
    ]
