# Generated by Django 5.2.4 on 2026-06-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderproduct_model_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="packaging_weight",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="order",
            name="product_weight",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(default="store", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="order",
            name="total_weight",
            field=models.FloatField(default=0.0),
        ),
    ]
