# Generated by Django 5.2.4 on 2026-06-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_packaging_weight_order_product_weight_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tax",
        ),
    ]
